### ISSUE TITLE
about 《FEND: A Future Enhanced Distribution-Aware Contrastive Learning Framework for Long-tail Trajectory Prediction》code

### ISSUE THREAD

**Issue by MSL502** [RLuke22/FJMP#2]
Dear author,
Hello, you gave to ‘’FEND: A Future Enhanced Distribution-Aware Contrastive Learning Framework for Long-tail Trajectory Prediction "code links to the code of other articles, Please check whether the link is incorrect

**Comment by RLuke22** [comment]
Hi, I believe you are referring to this [repository](https://github.com/colorfulfuture/Awesome-Trajectory-Motion-Prediction-Papers), which has linked the FJMP codebase to the wrong paper (FEND). I think it is better to raise an issue in that repository. Closing for this reason.

**Comment by colorfulfuture** [comment]
Hi,

I am the owner of that paper-list repo, sorry I put the wrong link. I already corrected it! I appreciate your interest in the repo.

Best,
Yi
