### ISSUE TITLE
 There is no command provided here for training on the Argoverse 2 dataset using a single GPU.

### ISSUE THREAD

**Issue by ouyangziyao** [RLuke22/FJMP#4]
Thank you for this excellent work, but I have a question.Here, there is no command provided for training on the Argoverse 2 dataset using a single GPU. However, there is such a command available for the INTERACTION dataset.Is it because the model's memory requirements exceed the memory limit of a single GPU?Do I have enough with only 12 GB of memory to run this model?

**Comment by RLuke22** [comment]
Hi,

Thanks for your interest in FJMP! I have modified the README to include the 1 GPU training for Argoverse 2. It is a simple modification to the 4 GPU command: remove the horovod commands at the beginning and multiply the batch size by 4 (from 32 to 128). 12GB of GPU memory should be enough to train an Argoverse 2 FJMP model on 1 GPU.
