### ISSUE TITLE
Argoverse2 Leaderboard

### ISSUE THREAD

**Issue by william-gx** [RLuke22/FJMP#5]
Dear authors,

Congratulations on this nice work being accepted!

We notice that the Leaderboard of Argoverse 2 multi-world forecasting has re-opened.  We would appreciate if you could provide the result on the test set for our comparison with your excellent work.

Best

**Comment by RLuke22** [comment]
Thanks for bringing this to our attention! We will upload FJMP onto the Argoverse 2 multi-world leaderboard within the next few days.

**Comment by RLuke22** [comment]
FJMP is now on the leaderboard. Thanks for your patience.
