### ISSUE TITLE
Question about submission file on INTERACTION Challenge

### ISSUE THREAD

**Issue by ChengkaiYang** [RLuke22/FJMP#7]
Hi,Luke:
     Sorry for disturbing again!When i want to evaluate FJMP result on INTERACTION leaderboard,i got no reply despite i follow all format requirements mentioned.Could you please provide your test result csv files so that i can see what format mistake i comitted when submitting result file.
     Moreover,INTERACTION dataset asks to submit psirad predictions.But I haven't find prediction about psirad in your model.
     Looking forward for a reply!Thanks!

**Comment by RLuke22** [comment]
Hi Chengkai,

To reproduce our results on the INTERACTION leaderboard, we retrain the models with both the train+validation datasets and use the checkpoint at the final epoch to build our submission. As the INTERACTION leaderboard is now open again, I will include the code to build the submission file (including how to derive the yaw predictions). This will be pushed in the next week - thanks for your patience.

**Comment by ChengkaiYang** [comment]
> Hi Chengkai,
> 
> To reproduce our results on the INTERACTION leaderboard, we retrain the models with both the train+validation datasets and use the checkpoint at the final epoch to build our submission. As the INTERACTION leaderboard is now open again, I will include the code to build the submission file (including how to derive the yaw predictions). This will be pushed in the next week - thanks for your patience.

Hi, Luke,
I found INTERACTION dataset's challenge benchmark might not exists now (website can't be open in my computer). When I try to open the leaderboard, the competition url page, http://[challenge.interaction-dataset.com](http://challenge.interaction-dataset.com/prediction-challenge/intro)/prediction-challenge/intro    got crashed. Have you met the same problem? If not, could you please tell me the correct challenge url? I would like to know does INTERACTION challenge use a new url which might be different from the old one? Thanks!

**Comment by ChengkaiYang** [comment]
> Hi Chengkai,
> 
> To reproduce our results on the INTERACTION leaderboard, we retrain the models with both the train+validation datasets and use the checkpoint at the final epoch to build our submission. As the INTERACTION leaderboard is now open again, I will include the code to build the submission file (including how to derive the yaw predictions). This will be pushed in the next week - thanks for your patience.

Hi, Luke,
I found INTERACTION dataset's challenge benchmark might not exists now (website can't be open in my computer). When I try to open the leaderboard, the competition url page, http://[challenge.interaction-dataset.com](http://challenge.interaction-dataset.com/prediction-challenge/intro)/prediction-challenge/intro    got crashed. Have you met the same problem? If not, could you please tell me the correct challenge url? I would like to know does INTERACTION challenge use a new url which might be different from the old one? Thanks!

**Comment by RLuke22** [comment]
> > Hi Chengkai,
> > To reproduce our results on the INTERACTION leaderboard, we retrain the models with both the train+validation datasets and use the checkpoint at the final epoch to build our submission. As the INTERACTION leaderboard is now open again, I will include the code to build the submission file (including how to derive the yaw predictions). This will be pushed in the next week - thanks for your patience.
> 
> Hi, Luke, I found INTERACTION dataset's challenge benchmark might not exists now (website can't be open in my computer). When I try to open the leaderboard, the competition url page, http://[challenge.interaction-dataset.com](http://challenge.interaction-dataset.com/prediction-challenge/intro)/prediction-challenge/intro got crashed. Have you met the same problem? If not, could you please tell me the correct challenge url? I would like to know does INTERACTION challenge use a new url which might be different from the old one? Thanks!

Yes, I'm facing the same problem, unfortunately. I will still release the test submission code in case the INTERACTION leaderboard goes live again.

**Comment by ChengkaiYang** [comment]
> > > Hi Chengkai,
> > > To reproduce our results on the INTERACTION leaderboard, we retrain the models with both the train+validation datasets and use the checkpoint at the final epoch to build our submission. As the INTERACTION leaderboard is now open again, I will include the code to build the submission file (including how to derive the yaw predictions). This will be pushed in the next week - thanks for your patience.
> > 
> > 
> > Hi, Luke, I found INTERACTION dataset's challenge benchmark might not exists now (website can't be open in my computer). When I try to open the leaderboard, the competition url page, http://[challenge.interaction-dataset.com](http://challenge.interaction-dataset.com/prediction-challenge/intro)/prediction-challenge/intro got crashed. Have you met the same problem? If not, could you please tell me the correct challenge url? I would like to know does INTERACTION challenge use a new url which might be different from the old one? Thanks!
> 
> Yes, I'm facing the same problem, unfortunately. I will still release the test submission code in case the INTERACTION leaderboard goes live again.

Thank you so much!

**Comment by ZheruiHuang** [comment]
@RLuke22 Hi，Luke，INTERACTION dataset's challenge benchmark is open now. Could you kindly release the test submission code? Thx.

**Comment by william-gx** [comment]
@RLuke22 Hi Luke, we notice that the INTERACTION leaderboard opens again. Could you kindly release the test submission code, especially code for deriving the yaw predictions. Many thanks.

**Comment by RLuke22** [comment]
@ChengkaiYang @william-gx Sorry for the delay on this. The repository is now updated with the INTERACTION test submission code, with instructions in the README.

**Comment by RLuke22** [comment]
@william-gx The code for deriving the yaw predictions can be found here: https://github.com/RLuke22/FJMP/blob/c8a57e50b96eac64cfc8f106a3c1ab11ff141362/fjmp_metrics.py#L53

**Comment by william-gx** [comment]
> @william-gx The code for deriving the yaw predictions can be found here:
> 
> https://github.com/RLuke22/FJMP/blob/c8a57e50b96eac64cfc8f106a3c1ab11ff141362/fjmp_metrics.py#L53

@RLuke22 Many thanks for your reply and the code.
